Microverse Portfolio
shahira-sadat/Portfolio pull request #1
Opened 2022-05-26 17:47 UTC by shahira-sadat

This is first part of Microverse portfolio.
Navigation bar and header sections added.

2022-05-26 18:39 UTC, danmainah requested changes
Hi @shahira-sadat , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design
✔️  Good PR and Description


# Required Changes ♻️
- [ ] Kindly add the get started section and a description to your readme file, making it more professional.
_Check the comments under the review._

## Optional suggestions



_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-26 18:39 UTC, danmainah commented on index.html
> +            <div class="all-item"><h1><a href="#">My Logo</a></h1></div>
- [ ] Kindly remove the logo from the `nav` tag, only the hamburger menu is supposed to have a `nav` tag.

2022-05-26 18:39 UTC, danmainah commented on index.html
> +            <div class="all-item"><h1><a href="#">My Logo</a></h1></div>
- [ ] Kindly check the alignment of your header section elements,make sure they align as in the design given

<img width="185" alt="image" src="https://user-images.githubusercontent.com/61408860/170553515-4be030fc-85f3-4227-b785-77ac57702395.png">

2022-05-26 18:39 UTC, danmainah commented on index.html
> +          <P class="connect">LET'S CONNECT</P>
- [ ] Kindy make sure your `LET'S CONNECT` has an `<a> or a `<button>` tag.This is because let's connect is a link.

2022-05-27 16:44 UTC, Mre55 requested changes
Hi @shahira-sadat 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

<img width="430" src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions 🟡 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 16:44 UTC, Mre55 commented on index.html
> +  </header>
As requested by the previous reviewer the `logo` should have to be out of the `nav` tag and inside the `header` tag. Here I put the general structure of how content inside the `header`  tag should have to be 👇 

```
<header>
    <a>Log...</a>
    <nav>...</nav>
</header>

```

2022-05-27 18:05 UTC, merged