Milestone2: Portfolio mobile version
shahira-sadat/Portfolio pull request #2
Opened 2022-05-28 16:56 UTC by shahira-sadat

Work Section and About Myself Section Added

2022-05-28 17:31 UTC, Chimwemwe-127001 requested changes
# Required Changes ♻️ :warning: 
### Hi @shahira-sadat<img src="https://user-images.githubusercontent.com/1303154/88677602-1635ba80-d120-11ea-84d8-d263ba5fc3c0.gif" width="19px" alt="hi">
Good job so far! :tada: 

There are some issues that you still need to work on to go to the next project but you are almost there! :pinching_hand: 

<img src="https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif" alt="so close">

## Highlights :+1: 
- Repo looks professional :briefcase:
- README.md looks professional :briefcase:

## Required Changes ♻️
***Check the comments under the review.***

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 17:31 UTC, Chimwemwe-127001 commented on index.html
> +        <div class="card-works">
- [ ] I suggest you use a `<section>` tag for this container. The `<section>` element is a semantic element; it provides meaning to both user agents and humans about the enclosed content — specifically, a section of the document. The sub-containers in this container can be just `divs`.

2022-05-28 17:31 UTC, Chimwemwe-127001 commented on index.html
> +        <div class="card-works">
- [ ] As the requirements suggest, In order to lay out the elements in the `"Works"` section you should use CSS Grid and Flexbox combined (it is mandatory that you use both). Use CSS Grid in the main container that contains all of the cards and use Flexbox to lay out an individual card.

2022-05-28 17:31 UTC, Chimwemwe-127001 commented on index.html
> +                </div>
- [ ] For this part of the portfolio, I suggest you closely follow the figma design.

Your design:
![image](https://user-images.githubusercontent.com/52143815/170836342-341c031c-2ff1-4aab-b4fa-99d19bf3cc84.png)

Figma design:
![image](https://user-images.githubusercontent.com/52143815/170836363-40c6ac93-165c-43ed-ac03-72cde620eccf.png)

2022-05-29 04:19 UTC, rotimiazeez approved these changes
# Hi Team👋 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-29 04:25 UTC, merged