Add contact form
shahira-sadat/Portfolio pull request #3
Opened 2022-05-31 19:53 UTC by shahira-sadat

In this pull, we(me and my coding partner) have worked on:
- Adding contactUs as footer 
- Designing form according to Figma design
- Adding Form validation
- Fixed textarea placeholder
- Fixed button placement
<img width="442" alt="Screen Shot 2022-06-01 at 12 18 14 PM" src="https://user-images.githubusercontent.com/53530780/171357224-28fa98ad-a581-403d-b5dd-6fe04803906f.png">

Kindly review it and share your feedback with me

2022-05-31 20:26 UTC, Ismailco requested changes
### Hi Team,

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 20:26 UTC, Ismailco commented on index.html
> +        <textarea
- [ ] The form will send even if the user didn't add a text message, please fix this you can remove the text inside the ```textarea``` (Write your message here) and replace it using a placeholder
- [ ] Please try to use a placeholder for the ```textarea```, it's a requirement

2022-05-31 20:26 UTC, Ismailco commented on index.html
> +        <button type="submit">Get in Touch</button>
- [ ] The submit button should be aligned to the left of the form, please pay more attention to details and try to creat the Figma design as close as possible

|Your design|Figma design|
|-|-|
|![Screenshot_20220531_212058](https://user-images.githubusercontent.com/25227022/171278261-abfe0008-bb5d-4d49-aeef-2dd8b2f6db48.png)|![Screenshot_20220531_212428](https://user-images.githubusercontent.com/25227022/171278284-75ada8a9-4a03-4d7b-b62a-aeee15ae7df9.png)|

2022-06-01 08:09 UTC, OLIPLICHE approved these changes
Hi @shahira-sadat , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 08:10 UTC, merged